service: backend-challenge

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  getAccount:
    handler: src/handler.getAccount
    events:
      - http:
          path: getAccount
          method: post
          cors: true

  addAccount:
    handler: src/handler.addAccount
    events:
      - http:
          path: addAccount
          method: post
          cors: true

  loadAccounts:
    handler: src/handler.loadAccounts
    events:
      - http:
          path: loadAccounts
          method: post
          cors: true

  makeTransaction:
    handler: src/handler.makeTransaction
    events:
      - http:
          path: makeTransaction
          method: post
          cors: true

  loadTransaction:
    handler: src/handler.loadTransaction
    events:
      - http:
          path: loadTransaction
          method: post
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
